_wandb:
    value:
        cli_version: 0.21.0
        e:
            jhravod0dszmvkaci6dgdtst6mz85o5y:
                codePath: scripts/train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "134862798848"
                        used: "542797824"
                email: savannah.ferretti@uci.edu
                executable: /global/homes/s/sferrett/.conda/envs/monsoon-sr/bin/python
                git:
                    commit: 16467861ffb5af9b2bc65060647d09f7fc8991b8
                    remote: https://github.com/savannahferretti/monsoon-sr.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-c148afbc-185d-689a-90c4-0890c0bd3fb7
                host: nid001060
                memory:
                    total: "269725601792"
                os: Linux-5.14.21-150500.55.97_13.0.78-cray_shasta_c-x86_64-with-glibc2.31
                program: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts/train.py
                python: CPython 3.10.18
                root: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts
                slurm:
                    cluster_name: perlmutter
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: m4334_g
                    job_cpus_per_node: "32"
                    job_end_time: "1755211340"
                    job_gid: "109311"
                    job_gpus: "0"
                    job_id: "41627321"
                    job_licenses: u1:1
                    job_name: jupyter
                    job_nodelist: nid001060
                    job_num_nodes: "1"
                    job_partition: shared_urgent_gpu_ss11
                    job_qos: gpu_shared_jupyter
                    job_start_time: "1755189740"
                    job_uid: "109311"
                    job_user: sferrett
                    jobid: "41627321"
                    localid: "0"
                    mem_per_cpu: "1796"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid001060
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nid001060
                    submit_dir: /global/u1/s/sferrett
                    submit_host: login01
                    task_pid: "1354707"
                    tasks_per_node: "1"
                    topology_addr: nid001060
                    topology_addr_pattern: node
                    tres_bind: gres/gpu:per_task:1
                    tres_per_task: cpu=32,gres/gpu=1
                startedAt: "2025-08-14T18:46:28.710386Z"
                writerId: jhravod0dszmvkaci6dgdtst6mz85o5y
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
architecture:
    value: MAE Deep
batch_size:
    value: 32000
experiment_number:
    value: "4"
feature_names:
    value:
        - subsatprofile_500
        - subsatprofile_550
        - subsatprofile_600
        - subsatprofile_650
        - subsatprofile_700
        - subsatprofile_750
        - subsatprofile_775
        - subsatprofile_800
        - subsatprofile_825
        - subsatprofile_850
        - subsatprofile_875
        - subsatprofile_900
        - subsatprofile_925
        - subsatprofile_950
        - subsatprofile_975
        - subsatprofile_1000
learning_rate:
    value: 0.0001
n_epochs:
    value: 30
n_features:
    value: 16
n_variables:
    value: 1
selected_variables:
    value:
        - subsatprofile
