name: monsoon-discovery
channels:
  - conda-forge
dependencies:
  - adlfs
  - basemap
  - bottleneck
  - cartopy
  - dask
  - fsspec
  - gcsfs
  - h5py
  - ipykernel
  - julia
  - matplotlib
  - netcdf4
  - numba
  - numpy
  - pandas
  - planetary-computer
  - proplot
  - pysr
  - pystac-client
  - python=3.10
  - pytorch
  - scikit-learn
  - scipy
  - sympy
  - wandb
  - xarray
  - xesmf
  - zarr