_wandb:
    value:
        cli_version: 0.21.0
        e:
            kdxtwutpux2zwq09ooswfy8lal20rf9f:
                codePath: scripts/nn.py
                codePathLocal: nn.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "134862786560"
                        used: "681435136"
                email: savannah.ferretti@uci.edu
                executable: /global/homes/s/sferrett/.conda/envs/monsoon-sr/bin/python
                git:
                    commit: 672a31223b17d786b9f390c77601a488332e56d3
                    remote: https://github.com/savannahferretti/monsoon-sr.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-bac5db23-b395-9a0f-5b9b-c3c9a1c8b0fb
                host: nid001764
                memory:
                    total: "269725573120"
                os: Linux-5.14.21-150500.55.97_13.0.78-cray_shasta_c-x86_64-with-glibc2.31
                program: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts/nn.py
                python: CPython 3.10.18
                root: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts
                slurm:
                    cluster_name: perlmutter
                    cpu_bind: quiet,mask_cpu:0x0000FFFF000000000000FFFF00000000
                    cpu_bind_list: 0x0000FFFF000000000000FFFF00000000
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "32"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: m4334_g
                    job_cpus_per_node: "32"
                    job_end_time: "1757049126"
                    job_gid: "109311"
                    job_gpus: "2"
                    job_id: "42477724"
                    job_licenses: cfs:1
                    job_name: nn
                    job_nodelist: nid001764
                    job_num_nodes: "1"
                    job_partition: shared_gpu_ss11
                    job_qos: gpu_shared
                    job_start_time: "1757038326"
                    job_uid: "109311"
                    job_user: sferrett
                    jobid: "42477724"
                    launch_node_ipaddr: 128.55.67.124
                    localid: "0"
                    mem_per_cpu: "1796"
                    mpi_type: cray_shasta
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid001764
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 128.55.67.124
                    srun_comm_port: "36779"
                    step_gpus: "2"
                    step_id: "0"
                    step_launcher_port: "36779"
                    step_nodelist: nid001764
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 63419-63420
                    step_tasks_per_node: "1"
                    stepid: "0"
                    stepmgr: nid001764
                    submit_dir: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts
                    submit_host: login20
                    task_pid: "2322633"
                    tasks_per_node: "1"
                    topology_addr: nid001764
                    topology_addr_pattern: node
                    umask: "0002"
                startedAt: "2025-09-05T02:23:06.477320Z"
                writerId: kdxtwutpux2zwq09ooswfy8lal20rf9f
        m:
            - "1": Training loss
              "5": 2
              "6":
                - 1
                - 3
              "7":
                - 6
            - "1": Epoch
              "6":
                - 3
              "7":
                - 6
            - "1": Validation loss
              "5": 2
              "6":
                - 1
                - 3
              "7":
                - 6
            - "1": Learning rate
              "5": 2
              "6":
                - 1
                - 3
              "7":
                - 6
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 7
                - 13
                - 16
                - 62
                - 63
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
Early stopping patience:
    value: 3
Initial learning rate:
    value: 0.0001
Input variables:
    value: '"cape", "subsat"'
Learning rate scheduler:
    value: ReduceLROnPlateau (factor=0.5)
Loss function:
    value: Mean squared error
Maximum training epochs:
    value: 30
Model parameter count:
    value: 44993
Network architecture:
    value: 256→128→64→32→1 (GELU + BatchNorm)
Optimizer:
    value: Adam
Training batch size:
    value: 64000
