_wandb:
    value:
        cli_version: 0.21.0
        e:
            cyfr4od8e7mmxqvvqurrcbhpwqp2kqmu:
                codePath: scripts/nn_new.py
                codePathLocal: nn_new.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "134860541952"
                        used: "617635840"
                email: savannah.ferretti@uci.edu
                executable: /global/homes/s/sferrett/.conda/envs/monsoon-sr/bin/python
                git:
                    commit: 672a31223b17d786b9f390c77601a488332e56d3
                    remote: https://github.com/savannahferretti/monsoon-sr.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-252fe412-3f22-a344-9ce5-bba8a604e10f
                host: nid003605
                memory:
                    total: "269721088000"
                os: Linux-5.14.21-150500.55.97_13.0.78-cray_shasta_c-x86_64-with-glibc2.31
                program: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts/nn_new.py
                python: CPython 3.10.18
                root: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts
                slurm:
                    cluster_name: perlmutter
                    cpu_bind: quiet,mask_cpu:0x0000FFFF000000000000FFFF00000000
                    cpu_bind_list: 0x0000FFFF000000000000FFFF00000000
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "32"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: m4334_g
                    job_cpus_per_node: "32"
                    job_end_time: "1756503988"
                    job_gid: "109311"
                    job_gpus: "2"
                    job_id: "42160878"
                    job_licenses: cfs:1
                    job_name: nn
                    job_nodelist: nid003605
                    job_num_nodes: "1"
                    job_partition: shared_gpu_ss11
                    job_qos: gpu_shared
                    job_start_time: "1756496788"
                    job_uid: "109311"
                    job_user: sferrett
                    jobid: "42160878"
                    launch_node_ipaddr: 128.55.68.142
                    localid: "0"
                    mem_per_cpu: "1796"
                    mpi_type: cray_shasta
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid003605
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 128.55.68.142
                    srun_comm_port: "42635"
                    step_gpus: "2"
                    step_id: "0"
                    step_launcher_port: "42635"
                    step_nodelist: nid003605
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 63191-63192
                    step_tasks_per_node: "1"
                    stepid: "0"
                    stepmgr: nid003605
                    submit_dir: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts
                    submit_host: login21
                    task_pid: "1856057"
                    tasks_per_node: "1"
                    topology_addr: nid003605
                    topology_addr_pattern: node
                    umask: "0002"
                startedAt: "2025-08-29T19:56:23.748434Z"
                writerId: cyfr4od8e7mmxqvvqurrcbhpwqp2kqmu
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
Early Stopping Patience:
    value: 3
Initial Learning Rate:
    value: 0.001
Input Variables:
    value:
        - cape
        - subsat
Learning Rate Scheduler:
    value: ReduceLROnPlateau (factor=0.5)
Loss Function:
    value: Mean Squared Error
Maximum Training Epochs:
    value: 30
Model Parameter Count:
    value: 44033
Network Architecture:
    value: 256→128→64→32→1 (GELU + BatchNorm)
Optimizer:
    value: Adam
Training Batch Size:
    value: 64000
